// Bundles apps/ops-console into a single self-contained HTML string and emits
// src/generated/ops-console-html.ts so plain tsc (and the npm tarball) need no
// knowledge of esbuild. Run before tsc: `npm run build:apps`.
import * as esbuild from "esbuild";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const entry = path.join(root, "apps/ops-console/main.tsx");
const outFile = path.join(root, "src/generated/ops-console-html.ts");
const watch = process.argv.includes("--watch");

const buildOptions = {
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  minify: true,
  jsx: "automatic",
  jsxImportSource: "preact",
  write: false,
  outdir: "out", // virtual; write:false keeps output in memory
  define: { "process.env.NODE_ENV": '"production"' },
};

function emit(result) {
  const js = result.outputFiles.find((f) => f.path.endsWith(".js"))?.text ?? "";
  const css =
    result.outputFiles.find((f) => f.path.endsWith(".css"))?.text ?? "";
  const template = readFileSync(
    path.join(root, "apps/ops-console/index.html"),
    "utf8",
  );
  // Function replacers: literal insertion, no $-pattern interpretation.
  const html = template
    .replace("/*__CSS__*/", () => css)
    .replace("/*__JS__*/", () => js);
  const module_ =
    "// GENERATED by scripts/build-apps.mjs — do not edit; gitignored.\n" +
    `export const OPS_CONSOLE_HTML: string = ${JSON.stringify(html)};\n`;
  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, module_);
  console.log(
    `build-apps: wrote ${path.relative(root, outFile)} (${(html.length / 1024).toFixed(1)} KB)`,
  );
}

if (watch) {
  const ctx = await esbuild.context({
    ...buildOptions,
    plugins: [
      {
        name: "emit",
        setup: (b) => b.onEnd((r) => r.errors.length === 0 && emit(r)),
      },
    ],
  });
  await ctx.watch();
  console.log("build-apps: watching…");
} else {
  emit(await esbuild.build(buildOptions));
}
